name: My CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["uat", "production"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8
    - name: Terraform Init uat
      if: github.event.inputs.workspace == 'uat'
      run: terraform init -backend-config="workspace=uat"
    - name: Terraform Init prod
      if: github.event.inputs.workspace == 'production'
      run: terraform init -backend-config="workspace=production"
      
    - name: Prompt user for input
      run: |
          echo "Do you want to continue?"
          read -r answer
          echo "You answered: $answer"
    - name: Check user input
      run: |
          if [[ "$answer" == "yes" ]]; then
            echo "Continuing the workflow ..."
          else
            echo "Stopping the workflow ..."
            exit 1
          fi
    - name: Do something
      run: echo "Doing something ..."
      
      
      
      
      
    - name: Print input value
      run: echo "The 'my_boolean_input' value is ${{ github.event.inputs.my_boolean_input }}"
    - name: Do something if input is true
      if: github.event.inputs.my_boolean_input == 'true'
      run: echo "The 'my_boolean_input' is true, doing something ..."
      
    - name: Terraform Apply
      if: github.event.inputs.destroy != 'true'
      run: echo terraform apply !!!!!!!!!!!!!!!!!!!!!!!!!
    - name: Terraform Destroy
      if: github.event.inputs.destroy == 'true'
      run: echo destroy !!!!!!!!!!!!!!!!!!!!!!!!!!!
      
    env:
      TF_INPUT: 0
      TF_REATTACH_PROVIDERS: 1

    outputs:
      destroy: ${{ github.event.inputs.destroy }}
