name: My CI/CD Pipeline


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: echo build
      
  DeployUAT:
    name: DeployUAT
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: UAT
    steps:
      - name: deploying
        run: echo deploying
  DeployProd:
    name: DeployProd
    if: github.event_name == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - name: deploying
        run: echo deploying
   
