name: My CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["uat", "production"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8
    - name: Terraform Init
      run: echo terraform inti
    - name: Terraform Apply
      if: github.event.inputs.destroy != 'true'
      run: echo terraform apply
    - name: Terraform Destroy
      if: github.event.inputs.destroy == 'true'
      run: echo terraform destroy
   
    env:
      TF_INPUT: 0
      TF_REATTACH_PROVIDERS: 1


    outputs:
      destroy: ${{ github.event.inputs.destroy }}
