name: My CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["uat", "production"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8
    - name: Terraform Init uat
      if: github.event.inputs.workspace == 'uat'
      run: terraform init -backend-config="workspace=uat"
    - name: Terraform Init prod
      if: github.event.inputs.workspace == 'production'
      run: terraform init -backend-config="workspace=production"
    - name: Terraform Apply
      if: github.event.inputs.destroy != 'true'
      run: terraform apply -var-file=${{ github.event.inputs.workspace }}.tfvars
    - name: Terraform Destroy
      if: github.event.inputs.destroy == 'true'
      run: terraform destroy -var-file=${{ github.event.inputs.workspace }}.tfvars

    env:
      TF_INPUT: 0
      TF_REATTACH_PROVIDERS: 1

    outputs:
      destroy: ${{ github.event.inputs.destroy }}
