name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pause Workflow
        id: pause
        uses: "actions/github-script@v5"
        with:
          script: echo "Workflow paused. Waiting for approval."
        
      - name: Continue Workflow
        if: github.event_name == 'workflow_dispatch' || steps.pause.outputs.approved == 'true'
        run: echo "Workflow continued."

      - name: Next Step
        run: echo "Perform the next step after resuming."

