name: Terraform Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: [uat, prod]

    steps:
    - uses: actions/checkout@v2
    - name: Terraform Init
      run: echo terraform init
    - name: Terraform Apply or Destroy
      if: ${{ !steps.check_params.outputs.destroy }}
      run: echo terraform apply
      else:
        run: echo terrafrom destory

    outputs:
      destroy: ${{ github.event.inputs.destroy }}
