name: Terraform Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: [uat, prod]

    steps:
    - uses: actions/checkout@v2
    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply or Destroy
      if: ${{ !steps.check_params.outputs.destroy }}
      run: terraform apply -var-file=${{ matrix.workspace }}.tfvars
      else:
        run: terraform destroy -var-file=${{ matrix.workspace }}.tfvars

    outputs:
      destroy: ${{ github.event.inputs.destroy }}
